/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package udistrital.avanzada.taller1.vista;

import java.awt.Dimension;
import java.net.URL;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.SwingConstants;

/**
 *
 * author mauri
 */
public class PanelGaleria extends javax.swing.JPanel {

    /**
     * Creates new form PanelGaleria
     */
    public PanelGaleria() {
        initComponents(); 
        // dejar que el scroll vertical sea infinito
        scrollListaProductos.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        // no permitir el scroll horizontal
        scrollListaProductos.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        // velocida del scroll
        scrollListaProductos.getVerticalScrollBar().setUnitIncrement(20);
        // para que los elementos se apilen
        panelContenido.setLayout(new BoxLayout(panelContenido, BoxLayout.Y_AXIS));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bBuscarItem = new javax.swing.JButton();
        scrollListaProductos = new javax.swing.JScrollPane();
        panelContenido = new javax.swing.JPanel();

        jLabel2.setText("Cedula Proveedor");

        bBuscarItem.setText("Buscar");
        bBuscarItem.setActionCommand("BuscarItemsPorProveedor");
        bBuscarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelContenidoLayout = new javax.swing.GroupLayout(panelContenido);
        panelContenido.setLayout(panelContenidoLayout);
        panelContenidoLayout.setHorizontalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );
        panelContenidoLayout.setVerticalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 223, Short.MAX_VALUE)
        );

        scrollListaProductos.setViewportView(panelContenido);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollListaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bBuscarItem))
                            .addComponent(jLabel2))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBuscarItem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollListaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public void mostrarInsumoEnLista(String nombre,String descripcion ,String duracion, String precio, String id, String creador, String imagen){
        PanelItemServicio aux = new PanelItemServicio();
        aux.lDuracion.setText("Duracion "+duracion +" min");
        aux.txtDescripcion.setText(descripcion);
        aux.lNombre.setText(nombre);
        aux.lPrecio.setText(precio);
        aux.lId.setText("ID "+id);
        aux.lCreador.setText("Por "+creador);
        // verificar url
        URL url = getClass().getResource(imagen);
        // si exite entonces poner la imagen
        if (url != null) {
            ImageIcon icon = new ImageIcon(url);
            aux.bImagen.setIcon(icon);      
        }
        // agergar el item al panel donde se mostraraa
        panelContenido.add(aux);
        // separador visual
        JSeparator separador = new JSeparator(SwingConstants.HORIZONTAL);
        // linea delgada y horizontal
        separador.setMaximumSize(new Dimension(Integer.MAX_VALUE, 1)); // para que se estire
        // agregar separador
        panelContenido.add(separador);
        // Recalcula el layout para que se muestren los objetos
        panelContenido.revalidate(); 
        panelContenido.repaint(); 
    }
    
    public void mostrarServicioALista(String nombre,String descripcion ,String cantidad, String precio, String id, String creador, String imagen){
        PanelItemInsumo aux = new PanelItemInsumo();
        aux.lCantidad.setText("Hay "+cantidad);
        aux.txtDescripcion.setText(descripcion);
        aux.lNombre.setText(nombre);
        aux.lPrecio.setText(precio);
        aux.lId.setText("ID "+id);
        aux.lCreador.setText("Por "+creador);
        
        URL url = getClass().getResource(imagen);
        if (url != null) {
            ImageIcon icon = new ImageIcon(url);
            aux.bImagen.setIcon(icon);      
        }
        
        panelContenido.add(aux);
        JSeparator separador = new JSeparator(SwingConstants.HORIZONTAL);
        separador.setMaximumSize(new Dimension(Integer.MAX_VALUE, 1)); // para que se estire
        panelContenido.add(separador);
        panelContenido.revalidate(); // Recalcula el layout
        panelContenido.repaint(); 
    }
    
    private void limpiarPanelContenido() {
        panelContenido.removeAll();
        panelContenido.revalidate();
        panelContenido.repaint();
    }
    
    private void bBuscarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bBuscarItemActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bBuscarItem;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JScrollPane scrollListaProductos;
    // End of variables declaration//GEN-END:variables
}
