/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package udistrital.avanzada.taller1.vista;

/**
 *
 * @author mauri
 */
public class PanelServicio extends javax.swing.JPanel {

    /**
     * Creates new form PanelServicio
     */
    public PanelServicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcVisibilidad = new javax.swing.ButtonGroup();
        opcNoVisible = new javax.swing.JRadioButton();
        lMarca = new javax.swing.JLabel();
        lColor1 = new javax.swing.JLabel();
        bCrearInsumo = new javax.swing.JButton();
        bMisServicios = new javax.swing.JButton();
        cNombre = new javax.swing.JTextField();
        lAno = new javax.swing.JLabel();
        lPotencia = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cDescripcion = new javax.swing.JTextArea();
        cPrecio = new javax.swing.JTextField();
        lColor = new javax.swing.JLabel();
        cDuracion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        optVisible = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(400, 300));

        opcVisibilidad.add(opcNoVisible);
        opcNoVisible.setText("no");
        opcNoVisible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcNoVisibleActionPerformed(evt);
            }
        });

        lMarca.setText("Nombre:");

        lColor1.setText("Visible:");

        bCrearInsumo.setText("Crear");
        bCrearInsumo.setActionCommand("CrearInsumo");
        bCrearInsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearInsumoActionPerformed(evt);
            }
        });

        bMisServicios.setText("Mis servicios");
        bMisServicios.setActionCommand("MisServicios");
        bMisServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMisServiciosActionPerformed(evt);
            }
        });

        cNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cNombreActionPerformed(evt);
            }
        });

        lAno.setText("Descripcion:");

        lPotencia.setText("Precio:");

        cDescripcion.setColumns(20);
        cDescripcion.setRows(5);
        jScrollPane2.setViewportView(cDescripcion);

        cPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cPrecioActionPerformed(evt);
            }
        });

        lColor.setText("Duracion:");

        cDuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cDuracionActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingrese los datos de su insumo");

        opcVisibilidad.add(optVisible);
        optVisible.setText("si");
        optVisible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optVisibleActionPerformed(evt);
            }
        });

        jLabel2.setText("Imagen:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lMarca, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lColor1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lAno, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lPotencia, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lColor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(optVisible)
                                .addGap(9, 9, 9)
                                .addComponent(opcNoVisible))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(bMisServicios)
                        .addGap(172, 172, 172)
                        .addComponent(bCrearInsumo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel1)))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lMarca)
                    .addComponent(cNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lAno)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lColor, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(opcNoVisible, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lColor1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(optVisible, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bMisServicios)
                    .addComponent(bCrearInsumo))
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void opcNoVisibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcNoVisibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcNoVisibleActionPerformed

    private void bCrearInsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearInsumoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCrearInsumoActionPerformed

    private void bMisServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMisServiciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bMisServiciosActionPerformed

    private void cNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cNombreActionPerformed

    private void cPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cPrecioActionPerformed

    private void cDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cDuracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cDuracionActionPerformed

    private void optVisibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optVisibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optVisibleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bCrearInsumo;
    public javax.swing.JButton bMisServicios;
    private javax.swing.JTextArea cDescripcion;
    private javax.swing.JTextField cDuracion;
    public javax.swing.JTextField cNombre;
    private javax.swing.JTextField cPrecio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lAno;
    private javax.swing.JLabel lColor;
    private javax.swing.JLabel lColor1;
    private javax.swing.JLabel lMarca;
    private javax.swing.JLabel lPotencia;
    private javax.swing.JRadioButton opcNoVisible;
    private javax.swing.ButtonGroup opcVisibilidad;
    private javax.swing.JRadioButton optVisible;
    // End of variables declaration//GEN-END:variables
}
