/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package udistrital.avanzada.taller1.vista;

import java.awt.Dimension;
import java.net.URL;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.SwingConstants;

/**
 *
 * @author mauricio
 * La clase muestra todos los vehiculos y permite puede
 * llevar al usuario a editar o borrar un vehiculo
 */
public class PanelVehiculos extends javax.swing.JPanel {

    /**
     * Creates new form PanelVehicullos
     */
    public PanelVehiculos() {
        initComponents();
        // dejar que el scroll vertical sea infinito
        scrollListaVehiculos.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        // no permitir el scroll horizontal
        scrollListaVehiculos.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        // velocida del scroll
        scrollListaVehiculos.getVerticalScrollBar().setUnitIncrement(20);
        // para que los elementos se apilen
        panelContenido.setLayout(new BoxLayout(panelContenido, BoxLayout.Y_AXIS));
    }
    /**
     * metodo para mostrar un vehiculo
     * @param marca
     * @param modelo
     * @param ano
     * @param potencia
     * @param color
     * @param tipoVehiculo
     * @param placa 
     */
    public void mostrarVehiculoEnLista(String marca, String modelo, String ano, String potencia, String color, String tipoVehiculo, String placa, String imagen){
        // creamos un panel del item vehiculo
        PanelItemVehiculo aux = new PanelItemVehiculo();
        //seteamos los atributos a mostrar
        aux.lAño.setText("Año "+ano);
        aux.lColor.setText("Color "+color);
        aux.lMarca.setText("Marca "+marca);
        aux.lPlaca.setText("Placa "+placa);
        aux.lPotencia.setText("Potencia "+potencia+"W");
        aux.lTipo.setText(tipoVehiculo);    
        //comprobar si esta la imagen
        URL url = getClass().getResource(imagen);
        // si exite entonces poner la imagen
        if (url != null) {
            //poner la imagen
            ImageIcon icon = new ImageIcon(url);
            aux.bImagen.setIcon(icon);      
        }
        //action command de los botontes con el identificador
        aux.bBorrar.setActionCommand("BorrarVehiculo-"+placa);
        aux.bEditar.setActionCommand("EditarVehiculo-"+placa);
        
        // agregar el item al panel donde se mostraraa
        panelContenido.add(aux);
        // separador visual
        JSeparator separador = new JSeparator(SwingConstants.HORIZONTAL);
        // linea delgada y horizontal
        separador.setMaximumSize(new Dimension(Integer.MAX_VALUE, 1)); // para que se estire
        // agregar separador
        panelContenido.add(separador);
        // Recalcula el layout para que se muestren los objetos
        panelContenido.revalidate(); 
        panelContenido.repaint(); 
    }
    
    /**
     * metodo para limpiar del panel contenido que tiene 
     * renderiza los vehicullos
     */   
    public void limpiarPanelContenido() {
        panelContenido.removeAll();
        panelContenido.revalidate();
        panelContenido.repaint();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        scrollListaVehiculos = new javax.swing.JScrollPane();
        panelContenido = new javax.swing.JPanel();
        bBuscarVehiculos = new javax.swing.JButton();

        setBackground(new java.awt.Color(243, 229, 139));

        jLabel1.setText("Mis Vehiculos");

        javax.swing.GroupLayout panelContenidoLayout = new javax.swing.GroupLayout(panelContenido);
        panelContenido.setLayout(panelContenidoLayout);
        panelContenidoLayout.setHorizontalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );
        panelContenidoLayout.setVerticalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 241, Short.MAX_VALUE)
        );

        scrollListaVehiculos.setViewportView(panelContenido);

        bBuscarVehiculos.setText("buscar");
        bBuscarVehiculos.setActionCommand("ActualizarListaVehiculosUsuario");
        bBuscarVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarVehiculosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bBuscarVehiculos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(scrollListaVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBuscarVehiculos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollListaVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bBuscarVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarVehiculosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bBuscarVehiculosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bBuscarVehiculos;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JPanel panelContenido;
    private javax.swing.JScrollPane scrollListaVehiculos;
    // End of variables declaration//GEN-END:variables
}
