/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package udistrital.avanzada.taller1.vista;

/**
 *
 * @author user
 */
public class PanelLogin extends javax.swing.JPanel {

    /**
     * Creates new form PanelLogin
     */
    public PanelLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lUsuario = new javax.swing.JLabel();
        lContrasena = new javax.swing.JLabel();
        cUsuario = new javax.swing.JTextField();
        cContrasena = new javax.swing.JPasswordField();
        bMostrarContrasena = new javax.swing.JButton();
        bIniciarSesion = new javax.swing.JButton();
        bRegistrarse = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLogo = new javax.swing.JLabel();

        lUsuario.setText("Usuario");

        lContrasena.setText("Contraseña");

        bMostrarContrasena.setText("👁");
        bMostrarContrasena.setActionCommand("mostrarContrasena"
        );

        bIniciarSesion.setText("Iniciar Sesion");
        bIniciarSesion.setActionCommand("Iniciar Sesion");

        bRegistrarse.setText("Registrese");
        bRegistrarse.setActionCommand("Registrese");

        jLabel4.setText("¿Aun no tiene cuenta?");

        jLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/udistrital/avanzada/taller1/vista/rolaPet.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lUsuario)
                            .addComponent(lContrasena)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bMostrarContrasena))
                            .addComponent(cUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(bIniciarSesion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(bRegistrarse))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLogo)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(lUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lContrasena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bMostrarContrasena))
                .addGap(6, 6, 6)
                .addComponent(bIniciarSesion)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(bRegistrarse))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bIniciarSesion;
    public javax.swing.JButton bMostrarContrasena;
    public javax.swing.JButton bRegistrarse;
    public javax.swing.JPasswordField cContrasena;
    public javax.swing.JTextField cUsuario;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLogo;
    private javax.swing.JLabel lContrasena;
    private javax.swing.JLabel lUsuario;
    // End of variables declaration//GEN-END:variables
}
