/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package udistrital.avanzada.taller1.vista;

/**
 *
 * @author user
 */
public class PanelRegistro extends javax.swing.JPanel {

    /**
     * Creates new form PanelRegistro
     */
    public PanelRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTitulo = new javax.swing.JLabel();
        lNombre = new javax.swing.JLabel();
        lApellido = new javax.swing.JLabel();
        lCedula = new javax.swing.JLabel();
        lNumero = new javax.swing.JLabel();
        lCorreo = new javax.swing.JLabel();
        lMembresia = new javax.swing.JLabel();
        lContrasena = new javax.swing.JLabel();
        cApellido = new javax.swing.JTextField();
        cCedula = new javax.swing.JTextField();
        cNumero = new javax.swing.JTextField();
        cCorreo = new javax.swing.JTextField();
        cMembresia = new javax.swing.JTextField();
        cNombre = new javax.swing.JTextField();
        cContrasena = new javax.swing.JTextField();
        bRegistrar = new javax.swing.JButton();

        lTitulo.setText("Registro");

        lNombre.setText("Nombre: ");

        lApellido.setText("Apellido:");

        lCedula.setText("Cedula:");

        lNumero.setText("Numero:");

        lCorreo.setText("Correo:");

        lMembresia.setText("Membresia:");

        lContrasena.setText("Contraseña:");

        bRegistrar.setText("Registrar");
        bRegistrar.setActionCommand("Registrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lTitulo)
                .addGap(167, 167, 167))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lContrasena)
                    .addComponent(lMembresia)
                    .addComponent(lCorreo)
                    .addComponent(lNumero)
                    .addComponent(lCedula)
                    .addComponent(lApellido)
                    .addComponent(lNombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cApellido)
                    .addComponent(cCedula)
                    .addComponent(cNumero)
                    .addComponent(cCorreo)
                    .addComponent(cMembresia)
                    .addComponent(cNombre)
                    .addComponent(cContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addComponent(bRegistrar)
                .addGap(147, 147, 147))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(lTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNombre)
                    .addComponent(cNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lApellido)
                    .addComponent(cApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCedula)
                    .addComponent(cCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNumero)
                    .addComponent(cNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCorreo)
                    .addComponent(cCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lMembresia)
                    .addComponent(cMembresia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lContrasena)
                    .addComponent(cContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bRegistrar)
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bRegistrar;
    private javax.swing.JTextField cApellido;
    private javax.swing.JTextField cCedula;
    private javax.swing.JTextField cContrasena;
    private javax.swing.JTextField cCorreo;
    private javax.swing.JTextField cMembresia;
    private javax.swing.JTextField cNombre;
    private javax.swing.JTextField cNumero;
    private javax.swing.JLabel lApellido;
    private javax.swing.JLabel lCedula;
    private javax.swing.JLabel lContrasena;
    private javax.swing.JLabel lCorreo;
    private javax.swing.JLabel lMembresia;
    private javax.swing.JLabel lNombre;
    private javax.swing.JLabel lNumero;
    private javax.swing.JLabel lTitulo;
    // End of variables declaration//GEN-END:variables
}
